name: NATS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 10
    if: |
      !startsWith(github.event.head_commit.message, 'docs') &&
      !contains(github.event.head_commit.message, 'skip ci') &&
      !contains(github.event.head_commit.message, 'ci skip')

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      if: ${{ !env.ACT }}
      with:
          access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Test
      run: make nats-test
